title: Librarian
email: sids.1992@gmail.com
description: >- 
  Cause Local is best ğŸš€
baseurl: "" 
url: "" 
twitter_username: sids7
github_username:  biocross
host: 0.0.0.0

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
